version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:

      # Upgrade AWS CLI and boto3 to the latest version
      - pip install --upgrade awscli
      - pip install --upgrade boto3
      - pip install --user aws-sam-cli
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin
  
  pre_build:
    commands:

      # Discover and run unit tests in the 'tests' directory. For more information, see <https://docs.python.org/3/library/unittest.html#test-discovery>
      # - python -m unittest discover tests
  
  build:
    commands:

      # Use AWS SAM to package the application by using AWS CloudFormation
      - cd lambda
      - sam package --template api.yml --s3-bucket $S3_BUCKET --output-template ../api-export.yml


artifacts:
  type: zip
  files:
    - api-export.yml
